"""empty message

Revision ID: 5a2aabd35dfc
Revises: 
Create Date: 2026-03-02 11:59:57.892867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a2aabd35dfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False, comment="Human-readable document title, e.g. 'Regulation (EU) 965/2012'"),
    sa.Column('source_type', sa.Enum('pdf', 'odt', 'html', 'docx', 'txt', name='source_type', create_constraint=True), nullable=False, comment='Original file format before ingestion'),
    sa.Column('source_uri', sa.String(length=2048), nullable=True, comment='Original location (URL, S3 key, file path) of the source file'),
    sa.Column('jurisdiction', sa.Enum('easa', 'faa', 'icao', 'national', name='jurisdiction', create_constraint=True), nullable=False, comment='Regulatory body that issued the document'),
    sa.Column('doc_type', sa.Enum('regulation', 'implementing_rule', 'manual', 'guidance', 'aip', 'circular', name='doc_type', create_constraint=True), nullable=False, comment='Functional category: regulation, manual, guidance, etc.'),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False, comment="ISO 639-1 language code, e.g. 'en', 'fr', 'de'"),
    sa.Column('version_label', sa.String(length=100), nullable=True, comment="Human label like 'Amendment 12' or 'v3.4'"),
    sa.Column('effective_from', sa.Date(), nullable=True, comment='Date the document version enters into force'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Date the document version is superseded (NULL = still in force)'),
    sa.Column('published_at', sa.Date(), nullable=True, comment='Official publication date'),
    sa.Column('checksum', sa.String(length=128), nullable=False, comment='SHA-256 of the canonical source file; used for deduplication'),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True, comment='S3 bucket where the source file is stored'),
    sa.Column('s3_key', sa.String(length=2048), nullable=True, comment='S3 object key for the source file'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Size of the source file in bytes'),
    sa.Column('content_type', sa.String(length=255), nullable=True, comment='MIME type of the source file'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='Arbitrary extra fields (issuing authority, CELEX number, etc.)'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name='ck_documents_effective_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum', name='uq_documents_checksum')
    )
    op.create_index('ix_documents_effective_range', 'documents', ['effective_from', 'effective_to'], unique=False)
    op.create_index('ix_documents_jurisdiction_doc_type', 'documents', ['jurisdiction', 'doc_type'], unique=False)
    op.create_index('ix_documents_metadata', 'documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='Parent document this chunk belongs to'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='0-based position of this chunk within the document'),
    sa.Column('section_path', sa.String(length=1000), nullable=True, comment="Hierarchical path, e.g. 'Part-ORO > Subpart FC > ORO.FC.105'"),
    sa.Column('citation', sa.String(length=500), nullable=True, comment="Canonical citation label, e.g. 'Reg (EU) 965/2012, ORO.FC.105(a)'"),
    sa.Column('heading', sa.String(length=500), nullable=True, comment="Local heading or section title at this chunk's level"),
    sa.Column('text', sa.Text(), nullable=False, comment='Raw chunk text, used for quoting in RAG answers'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Approximate token count (model-specific); useful for context-window budgeting'),
    sa.Column('checksum', sa.String(length=128), nullable=False, comment='SHA-256 of the chunk text; prevents re-embedding identical content'),
    sa.Column('embedding', Vector(dim=1536), nullable=True, comment='Dense vector (1536-dim) for approximate nearest-neighbor search'),
    sa.Column('embedding_model', sa.String(length=200), nullable=True, comment="Identifier of the embedding model used, e.g. 'text-embedding-3-small'"),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_doc_index')
    )
    op.create_index('ix_chunks_checksum', 'document_chunks', ['checksum'], unique=False)
    op.create_index('ix_chunks_citation', 'document_chunks', ['citation'], unique=False)
    op.create_index('ix_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 200}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_updated_at'), 'document_chunks', ['updated_at'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('status', sa.Enum('started', 'success', 'failed', name='ingestion_status', create_constraint=True), server_default=sa.text("'started'"), nullable=False, comment='Lifecycle state: started → success | failed'),
    sa.Column('source_uri', sa.String(length=2048), nullable=False, comment='URI of the source being ingested in this run'),
    sa.Column('document_id', sa.Uuid(), nullable=True, comment='Linked document (set after successful creation/update)'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the run began'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='When the run completed (success or failure)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error traceback or message if the run failed'),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='Run statistics: chunk_count, token_total, duration_s, etc.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_document_id', 'ingestion_runs', ['document_id'], unique=False)
    op.create_index('ix_ingestion_runs_status', 'ingestion_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_updated_at'), 'ingestion_runs', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_runs_updated_at'), table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_status', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_document_id', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_document_chunks_updated_at'), table_name='document_chunks')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 200}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_document_id', table_name='document_chunks')
    op.drop_index('ix_chunks_citation', table_name='document_chunks')
    op.drop_index('ix_chunks_checksum', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index('ix_documents_metadata', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_jurisdiction_doc_type', table_name='documents')
    op.drop_index('ix_documents_effective_range', table_name='documents')
    op.drop_table('documents')

    # Drop enum types created by the upgrade
    op.execute("DROP TYPE IF EXISTS source_type")
    op.execute("DROP TYPE IF EXISTS jurisdiction")
    op.execute("DROP TYPE IF EXISTS doc_type")
    op.execute("DROP TYPE IF EXISTS ingestion_status")
    # ### end Alembic commands ###
