"""empty message

Revision ID: 6a0fb3f723d4
Revises: e974f2b62ef9
Create Date: 2026-03-07 16:37:03.438651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a0fb3f723d4'
down_revision: Union[str, None] = 'e974f2b62ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_logs',
    sa.Column('question', sa.Text(), nullable=False, comment="User's original question"),
    sa.Column('answer', sa.Text(), nullable=False, comment='Generated answer'),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of citation strings from the answer'),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='UUIDs of the retrieved context chunks'),
    sa.Column('model', sa.String(length=200), nullable=False, comment='LLM model used for generation'),
    sa.Column('top_k', sa.Integer(), nullable=False, comment='Number of chunks retrieved'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_logs_updated_at'), 'question_logs', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_logs_updated_at'), table_name='question_logs')
    op.drop_table('question_logs')
    # ### end Alembic commands ###
